- name: configuring frontend server
  hosts: frontend
  become: yes
  vars:

  tasks: # list of tasks
  - name: installing nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest

  - name: start and enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
  
  - name: removing all files in html folder
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: creating html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory